name: Enforce only dev merges into main
on:
  pull_request:
    branches:
      - main
jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dev as source branch
        if: github.head_ref != 'dev'
        run: |
          echo "Error: Pull requests to 'main' can only originate from the 'dev' branch."
          exit 1
